[CmdletBinding()]
param(
    [string]$ArtifactName = $(if ($env:EOS_ARTIFACT_NAME) { $env:EOS_ARTIFACT_NAME } else { "LeftBehindDev" }),
    [switch]$NonInteractive
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ($env:CI -and $env:CI -notmatch "^(0|false|no)$") {
    $NonInteractive = $true
}

function Read-RequiredValue {
    param(
        [Parameter(Mandatory = $true)]
        [string]$EnvironmentName,

        [Parameter(Mandatory = $true)]
        [string]$Prompt
    )

    $value = [Environment]::GetEnvironmentVariable($EnvironmentName)
    if ([string]::IsNullOrWhiteSpace($value)) {
        if ($NonInteractive) {
            throw "$EnvironmentName 환경 변수가 필요합니다."
        }

        $value = Read-Host $Prompt
    }

    if ([string]::IsNullOrWhiteSpace($value)) {
        throw "$Prompt 값은 비워 둘 수 없습니다."
    }

    return $value.Trim()
}

function Assert-Matches {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name,

        [Parameter(Mandatory = $true)]
        [string]$Value,

        [Parameter(Mandatory = $true)]
        [string]$Pattern,

        [Parameter(Mandatory = $true)]
        [string]$Message
    )

    if ($Value -cnotmatch $Pattern) {
        throw "$Name 형식이 올바르지 않습니다. $Message"
    }
}

$productId = Read-RequiredValue -EnvironmentName "EOS_PRODUCT_ID" -Prompt "EOS Product ID"
$sandboxId = Read-RequiredValue -EnvironmentName "EOS_SANDBOX_ID" -Prompt "EOS Dev Sandbox ID"
$deploymentId = Read-RequiredValue -EnvironmentName "EOS_DEPLOYMENT_ID" -Prompt "EOS Dev Deployment ID"
$clientId = Read-RequiredValue -EnvironmentName "EOS_CLIENT_ID" -Prompt "EOS 런타임 SDK Client ID (BPT 아님)"
$clientSecret = $env:EOS_CLIENT_SECRET
$secureSecret = $null

if ([string]::IsNullOrWhiteSpace($clientSecret)) {
    if ($NonInteractive) {
        throw "EOS_CLIENT_SECRET 환경 변수가 필요합니다."
    }

    $secureSecret = Read-Host "EOS 런타임 SDK Client Secret (화면에 표시되지 않음)" -AsSecureString
    $secretPointer = [IntPtr]::Zero

    try {
        $secretPointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureSecret)
        $clientSecret = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($secretPointer)
    }
    finally {
        if ($secretPointer -ne [IntPtr]::Zero) {
            [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($secretPointer)
        }
    }
}

if ([string]::IsNullOrWhiteSpace($clientSecret)) {
    throw "EOS 런타임 SDK Client Secret은 비워 둘 수 없습니다."
}

$clientSecret = $clientSecret.Trim()

Assert-Matches -Name "ArtifactName" -Value $ArtifactName -Pattern "^[A-Za-z][A-Za-z0-9_-]{2,63}$" -Message "영문자로 시작하는 3~64자의 영문자, 숫자, _, -만 사용하세요."
Assert-Matches -Name "Product ID" -Value $productId -Pattern "^[0-9a-fA-F]{32}$" -Message "Developer Portal의 Product ID를 확인하세요."
Assert-Matches -Name "Dev Sandbox ID" -Value $sandboxId -Pattern "^p-[a-z0-9]{20,}$" -Message "Live가 아닌 Dev 행의 p- 로 시작하는 Sandbox ID를 사용하세요."
Assert-Matches -Name "Dev Deployment ID" -Value $deploymentId -Pattern "^[0-9a-fA-F]{32}$" -Message "Dev Sandbox 아래 Dev Deployment ID를 확인하세요."
Assert-Matches -Name "SDK Client ID" -Value $clientId -Pattern "^xyz[A-Za-z0-9]{20,}$" -Message "런타임 SDK Client ID는 xyz로 시작해야 합니다. BPT Client ID를 넣지 마세요."
Assert-Matches -Name "SDK Client Secret" -Value $clientSecret -Pattern "^(?!\*+$)[A-Za-z0-9+/_-]{20,}$" -Message "별표로 가려진 값이 아닌 20자 이상의 실제 Base64/Base64URL 값을 사용하세요. UE 5.7 설정 파서 제한으로 =, 따옴표, 쉼표, 괄호는 사용할 수 없습니다."

$projectRoot = Split-Path -Parent $PSScriptRoot
$configDirectory = Join-Path $projectRoot "Config"
$outputPath = Join-Path $configDirectory "GeneratedEngine.ini"
$temporaryPath = "$outputPath.tmp"
$content = @"
; Generated by Scripts/SetupEOSDev.ps1. DO NOT COMMIT OR SHARE THIS FILE.
; Unreal Engine 5.7 loads Config/GeneratedEngine.ini after DefaultEngine.ini.

[/Script/OnlineSubsystemEOS.EOSSettings]
DefaultArtifactName="$ArtifactName"
!Artifacts=ClearArray
+Artifacts=(ArtifactName="$ArtifactName",ClientId="$clientId",ClientSecret="$clientSecret",ProductId="$productId",SandboxId="$sandboxId",DeploymentId="$deploymentId",ClientEncryptionKey="")
"@

try {
    if (-not (Test-Path -LiteralPath $configDirectory)) {
        New-Item -ItemType Directory -Path $configDirectory | Out-Null
    }

    $utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($temporaryPath, $content, $utf8WithoutBom)
    Move-Item -LiteralPath $temporaryPath -Destination $outputPath -Force
}
finally {
    if (Test-Path -LiteralPath $temporaryPath) {
        Remove-Item -LiteralPath $temporaryPath -Force
    }

    $content = $null
    $clientSecret = $null
    $secureSecret = $null
}

Write-Host "EOS Dev 로컬 설정을 생성했습니다: Config/GeneratedEngine.ini"
Write-Host "비밀키 값은 출력하지 않았으며 이 파일은 Git에서 제외됩니다."
